### PR TITLE
reduce dependencies

### PR DESCRIPTION
**Pull request by Pedro-Pessoa**
We were importing a few libs just because of a single constant value, instead, why not use the value directly?

From https://pkg.go.dev/golang.org/x/net/html/atom `Br` = 0x202

### CODE REVIEW

**Review by kamilon — COMMENTED** [review]
Because that is the whole point of libraries. The compiler will do the right thing and only pull in what is actually needed. These atom types will most likely be used more and more as we lean on goquery over regex.

**Comment by Pedro-Pessoa** [comment]
`Because that's the whole point of libraries`. It might be one point, but definitely not the whole point.

`The compiler will do the right thing and only pull in what is actually needed.` But we still need to download all dependencies because of a single constant value. 

`These atom types will most likely be used more and more as we lean on goquery over regex.` Good point! But when it happens, we can always import the package again if needed, but as of now, I can't seem to find a reason to have it. 

I don't see why we should remove the whole block though instead of what I did with this PR. 

Let me know what you think :)

**Comment by kamilon** [comment]
I'm fine with this change going in. I'd request that you put a comment above the const with the link to the doc you linked above. It'll make it easier to understand where we picked a random 0x202 :D

**Comment by Pedro-Pessoa** [comment]
Good point! Totally agree.
Will do!

**Review by tobiasehlert — APPROVED** [review]

**Pull request merged**
